import Head from "next/head";
import React, { Children, FC } from "react";
import Footer from "./Footer";
import Header from "./Header";
type LayoutType = {
    children: React.ReactNode;
    name: string;
};
const Layout: FC<LayoutType> = ({ children, name }) => {
    return (
        <>
            <Head>
                <title>{name}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main> {children}</main>
            <Footer />
        </>
    );
};

export default Layout;
